export const ZERO = 0
export const SALT_ROUNDS = 10

export const SECOND_PER_MINUTE = 60
export const MINUTE_PER_HOUR = 60
export const HOUR_PER_DAY = 24
export const DAY_PER_WEEK = 7

export const MILLIESCOND_PER_SECOND = 1000
export const MILLIESCOND_PER_MINUTE = MILLIESCOND_PER_SECOND * SECOND_PER_MINUTE
export const MILLIESCOND_PER_HOUR = MILLIESCOND_PER_MINUTE * MINUTE_PER_HOUR
export const MILLIESCOND_PER_DAY = MILLIESCOND_PER_HOUR * HOUR_PER_DAY
export const MILLIESCOND_PER_WEEK = MILLIESCOND_PER_DAY * DAY_PER_WEEK

export const DEFAULT_PORT = 3000
export const DEFAULT_DB_PORT = 3308

export const CUSTOMER_ADDRESS_LIMIT = 5

export const OTP_EXPIRE_TIME = CUSTOMER_ADDRESS_LIMIT * SECOND_PER_MINUTE * MILLIESCOND_PER_SECOND
export const OTP_EXPIRE_TIME_BY_MINUTE = 5

export const VARCHAR_LENGTH = 255

export const MIN_PASSWORD_LENGTH = 8
export const MAX_PASSWORD_LENGTH = 50

export const MIN_FULLNAME_LENGTH = 2
export const MAX_FULLNAME_LENGTH = 50

export const MIN_HASHED_PASSWORD_LENGTH = 50
export const MAX_HASHED_PASSWORD_LENGTH = 60

export const MIN_TOKEN_LENGTH = 40
export const MAX_TOKEN_LENGTH = 255

export const MIN_USERNAME_LENGTH = 3
export const MAX_USERNAME_LENGTH = 20

export const MIN_PHONE_NUMBER_LENGTH = 7
export const MAX_PHONE_NUMBER_LENGTH = 15

export const ACCESS_TOKEN_STATUS_CODE = 4001

export const REFRESH_TOKEN_STATUS_CODE = 4003

export const SIX = 6
export const FIVE = 5
