export * from './base.interface'
export * from './base.repo'
export { default as BioRepo } from './bio.repo'
export { default as ContactRepo } from './contact.repo'
export { default as CustomerAddressRepo } from './customer-address.repo'
export { default as DistrictRepo } from './district.repo'
export { default as EmailRepo } from './email.repo'
export { default as NetworkRepo } from './network.repo'
export { default as ProvinceRepo } from './province.repo'
export { default as RoleRepo } from './role.repo'
export { default as UserRepo } from './user.repo'
export { default as WardRepo } from './ward.repo'
